site_name: 准大学生入学指南

theme:
  name: material
  language: zh
  features:
    - navigation.tracking
    - navigation.top
    - toc.follow
    - search.highlight
    - search.suggest

nav:
  - 前言: index.md

  - 高考结束至出分前:
      - 专业认知: major.md
      - AI总结的专业介绍:
          - 阅读前提醒: 专业/index.md

          - 信息与电子类:
              - 计算机学院: 专业/计算机学院.md
              - 人工智能学院: 专业/人工智能学院.md
              - 微电子学院: 专业/微电子学院.md
              - 电气工程学院与自动化学院: 专业/电气工程学院与自动化学院.md

          - 工科类:
              - 船舶与海洋学院: 专业/船舶与海洋学院.md
              - 机械与动力学院: 专业/机械与动力学院.md
              - 材料科学与工程学院: 专业/材料科学与工程学院.md
              - 航空航天学院: 专业/航空航天学院.md
              - 环境科学与工程学院: 专业/环境科学与工程学院.md
              - 智慧能源创新学院: 专业/智慧能源创新学院.md

          - 理科类:
              - 数学科学学院: 专业/数学科学学院.md
              - 物理与天文学院: 专业/物理与天文学院.md
              - 化学化工学院: 专业/化学化工学院.md

          - 生命医学类:
              - 生命科学技术学院: 专业/生命科学技术学院.md
              - 生物医学工程学院: 专业/生物医学工程学院.md
              - 农业与生物学院: 专业/农业与生物学院.md
              - 上海交通大学医学院: 专业/上海交通大学医学院.md
              - 药学院: 专业/药学院.md

          - 经管与社科类:
              - 安泰经济与管理学院: 专业/安泰经济与管理学院.md
              - 国际与公共事务学院: 专业/国际与公共事务学院.md
              - 凯原法学院: 专业/凯原法学院.md

          - 人文与传播类:
              - 人文学院: 专业/人文学院.md
              - 外国语学院: 专业/外国语学院.md
              - 媒体与传播学院: 专业/媒体与传播学院.md

          - 设计、海洋与交叉项目:
              - 设计学院: 专业/设计学院.md
              - 海洋学院: 专业/海洋学院.md
              - 博渊未来技术学院: 专业/博渊未来技术学院.md

          - 清北补充方向:
              - 方向总览: 专业/清北补充方向.md
              - 建筑、城乡规划与风景园林: 专业/建筑城乡与风景园林.md
              - 水利、交通与工程管理: 专业/水利交通与工程管理.md
              - 测控仪器、微机电与工程物理: 专业/测控仪器与工程物理.md
              - 地球与空间科学: 专业/地球与空间科学.md
              - 心理学与认知科学: 专业/心理学与认知科学.md
              - 社会学、人类学与社会工作: 专业/社会学与人类学.md
              - 国际政治与外交学: 专业/国际政治与外交学.md
              - 图书馆学与信息管理: 专业/图书馆学与信息管理.md
              - 考古学与文博类: 专业/考古文博.md
              - 宗教学、逻辑学与科学史: 专业/宗教学逻辑学与科学史.md
              - 艺术史与美术设计: 专业/艺术史与美术设计.md

          - 浙大补充方向:
              - 方向总览: 专业/浙大补充方向.md
              - 农业科学、茶学与动物医学: 专业/农业科学、茶学与动物医学.md
              - 古典文献学: 专业/古典文献学.md
              - 土地资源管理与社会保障: 专业/土地资源管理与社会保障.md
              - 过程装备与控制工程: 专业/过程装备与控制工程.md
              - 光电信息科学与工程: 专业/光电信息科学与工程.md

  - 出分后至录取结果确定前:
      - 志愿填报: application.md

  - 录取结果确定后至大学开学前:
      - 推荐你看的一些资料: resource.md
      - 电脑: computer.md
      - 英语学习: english.md
      - 编程入门: programming.md
      - 大学生活准备: college-life.md
      - 开学防坑指南: safety.md
      - 写给想要转专业的同学: Change-of-Major.md
      - 写给计算机专业新生: cs-newcomer.md
  - 后记: last.md

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - admonition

extra_css:
  - stylesheets/extra.css
